travis:
  secure:
    BINSTAR_TOKEN: qwjUolGqjAcrww7UZp2WnMRsJwMSgh+gK45OQMdeHiS5toO20J4YEk1LoilPtYumAeTuq2L3at5GfjU8IntzpBL6QrwkOdGa2OoJAXOfDd2R27UM3VeWWedLlj2tzA4W7TGJ12hEnI7TQlahbte9USmRWEDuOAnvWgWOSrRLPtpHhvtlxDdTxyR4jYT+C3g8LUg0XOD8bJHeAdQ7bsciiPyvT4CYfRc3we4N9mq97qdfE3TURvA5CnLTbUMFCqazIaPZ6MsXuJixhWQX21Ju2Jmk4r1WLrf3uyup0GQNXYS/N37uPsEeCcxMonZDcS4uP1kY5ZpIY/NHkVvvHEklGsT8zUeVsWnBaGeaqInPErl88EhFEkPpgzHvUsVFUqspFtr815sxQw4KZ8QVvdc3qkFUo1Ef3nPUK97kz5ZbeIdhVHRtysWBiBsDo3sB/RId6839ltYqxfxID2USOHUoSmst90ptt8//GnzlOZDitycrpUg+71pU1s1CRtbRM5bDLJyok+nc6z/9Tc8jwExSP2CpBHMW016L6hLK77QHdw+6Qi3DNE9Gfe7aUqIUahaf7YHAnRP+p25O5ZHrlZLdmwKL6gm9cC3NS0O0z4ncMaps8fZwd9vk2Y5ALfmDVyKZY379VhJPmHOY0aE8cCRDoD8pwi6gwAod4rX6qVfL8xQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
